server:
  #端口号
  port: 8082

spring:
  datasource:
    #驱动
    driver-class-name: org.postgresql.Driver
    #url
    url: jdbc:postgresql://127.0.0.1:5432/postgres?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #账号
    username: postgres
    #密码
    password: 123456

  redis:
    #数据库索引(默认为0)
    database: 0
    #连接超时时间(单位毫秒)
    timeout: 500
    #IP
    host: 127.0.0.1
    #端口
    port: 6379
    jedis:
      pool:
        #连接池最大连接数
        max-active: 20
        #连接池最大阻塞时间
        max-wait: 500
        #连接池最大空闲连接
        max-idle: 10
        #连接池最小空闲连接
        min-idle: 5

  jackson:
    #时间格式化
    #date-format: yyyy-MM-dd HH:mm:ss
    #时区
    time-zone: GMT+8

logging:
  #日志等级(指定包下的)
  level:
    com:
      hik:
        seckill: debug
  #日志文件名称
  file: seckill-demo.log